# Generated by Django 3.2.8 on 2021-10-11 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_title', models.CharField(max_length=200, null=True)),
                ('F_image', models.ImageField(upload_to='images/')),
                ('F_language', models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('Simplified Chinese', 'Simplified Chinese'), ('Traditional Chinese', 'Traditional Chinese'), ('Vietnamese', 'Vietnamese'), ('Indonesian', 'Indonesian'), ('Thai', 'Thai'), ('German', 'German'), ('Russian', 'Russian'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('French', 'French')], max_length=20)),
                ('F_create_at', models.DateField(auto_now_add=True, null=True)),
                ('F_img_txt', models.TextField(null=True)),
                ('F_img_result', models.TextField(null=True)),
                ('F_img_Coordinate', models.TextField(null=True)),
                ('F_write', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
