# Generated by Django 3.2.8 on 2021-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionapp', '0002_alter_functioninfo_f_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functioninfo',
            name='F_language',
            field=models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('chinese', 'chinese'), ('vietnamese', 'vietnamese'), ('Indonesia', 'Indonesia'), ('arabic', 'arabic'), ('Bengal', 'Bengal'), ('german', 'german'), ('spanish', 'spanish'), ('french', 'french'), ('Hindi', 'Hindi'), ('italian', 'italian'), ('malaysian', 'malaysian'), ('dutch', 'dutch'), ('portukal ', 'portukal '), ('russian', 'russian'), ('thai', 'thai'), ('turkish', 'turkish')], max_length=25),
        ),
    ]
