# Generated by Django 3.2.8 on 2021-10-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
        ('functionapp', '0003_alter_functioninfo_f_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioninfo',
            name='F_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to='projectapp.project'),
        ),
    ]
