# Generated by Django 3.2.8 on 2021-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('l_title', models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('chinese', 'chinese'), ('vietnamese', 'vietnamese'), ('Indonesia', 'Indonesia'), ('arabic', 'arabic'), ('Bengal', 'Bengal'), ('german', 'german'), ('spanish', 'spanish'), ('french', 'french'), ('Hindi', 'Hindi'), ('italian', 'italian'), ('malaysian', 'malaysian'), ('dutch', 'dutch'), ('portukal ', 'portukal '), ('russian', 'russian'), ('thai', 'thai'), ('turkish', 'turkish')], max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
